#![doc = "Peripheral access API for GD32E231 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 4;
#[cfg(feature = "rt")]
pub use self::Interrupt as interrupt;
#[cfg(feature = "rt")]
pub use cortex_m_rt::interrupt;
#[cfg(feature = "rt")]
extern "C" {
    fn WWDGT();
    fn LVD();
    fn RTC();
    fn FMC();
    fn RCU();
    fn EXTI0_1();
    fn EXTI2_3();
    fn EXTI4_15();
    fn DMA_Channel0();
    fn DMA_Channel1_2();
    fn DMA_Channel3_4();
    fn ADC_CMP();
    fn TIMER0_BRK_UP_TRG_COM();
    fn TIMER0_CC();
    fn TIMER2();
    fn TIMER5();
    fn TIMER13();
    fn TIMER14();
    fn TIMER15();
    fn TIMER16();
    fn I2C0_EV();
    fn I2C1_EV();
    fn SPI0();
    fn SPI1();
    fn USART0();
    fn USART1();
    fn I2C0_ER();
    fn I2C1_ER();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 35] = [
    Vector { _handler: WWDGT },
    Vector { _handler: LVD },
    Vector { _handler: RTC },
    Vector { _handler: FMC },
    Vector { _handler: RCU },
    Vector { _handler: EXTI0_1 },
    Vector { _handler: EXTI2_3 },
    Vector { _handler: EXTI4_15 },
    Vector { _reserved: 0 },
    Vector {
        _handler: DMA_Channel0,
    },
    Vector {
        _handler: DMA_Channel1_2,
    },
    Vector {
        _handler: DMA_Channel3_4,
    },
    Vector { _handler: ADC_CMP },
    Vector {
        _handler: TIMER0_BRK_UP_TRG_COM,
    },
    Vector {
        _handler: TIMER0_CC,
    },
    Vector { _reserved: 0 },
    Vector { _handler: TIMER2 },
    Vector { _handler: TIMER5 },
    Vector { _reserved: 0 },
    Vector { _handler: TIMER13 },
    Vector { _handler: TIMER14 },
    Vector { _handler: TIMER15 },
    Vector { _handler: TIMER16 },
    Vector { _handler: I2C0_EV },
    Vector { _handler: I2C1_EV },
    Vector { _handler: SPI0 },
    Vector { _handler: SPI1 },
    Vector { _handler: USART0 },
    Vector { _handler: USART1 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: I2C0_ER },
    Vector { _reserved: 0 },
    Vector { _handler: I2C1_ER },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - WWDGT"]
    WWDGT = 0,
    #[doc = "1 - LVD"]
    LVD = 1,
    #[doc = "2 - RTC"]
    RTC = 2,
    #[doc = "3 - FMC"]
    FMC = 3,
    #[doc = "4 - RCU"]
    RCU = 4,
    #[doc = "5 - EXTI0_1"]
    EXTI0_1 = 5,
    #[doc = "6 - EXTI2_3"]
    EXTI2_3 = 6,
    #[doc = "7 - EXTI4_15"]
    EXTI4_15 = 7,
    #[doc = "9 - DMA_Channel0"]
    DMA_Channel0 = 9,
    #[doc = "10 - DMA_Channel1_2"]
    DMA_Channel1_2 = 10,
    #[doc = "11 - DMA_Channel3_4"]
    DMA_Channel3_4 = 11,
    #[doc = "12 - ADC_CMP"]
    ADC_CMP = 12,
    #[doc = "13 - TIMER0_BRK_UP_TRG_COM"]
    TIMER0_BRK_UP_TRG_COM = 13,
    #[doc = "14 - TIMER0_CC"]
    TIMER0_CC = 14,
    #[doc = "16 - TIMER2"]
    TIMER2 = 16,
    #[doc = "17 - TIMER5"]
    TIMER5 = 17,
    #[doc = "19 - TIMER13"]
    TIMER13 = 19,
    #[doc = "20 - TIMER14"]
    TIMER14 = 20,
    #[doc = "21 - TIMER15"]
    TIMER15 = 21,
    #[doc = "22 - TIMER16"]
    TIMER16 = 22,
    #[doc = "23 - I2C0_EV"]
    I2C0_EV = 23,
    #[doc = "24 - I2C1_EV"]
    I2C1_EV = 24,
    #[doc = "25 - SPI0"]
    SPI0 = 25,
    #[doc = "26 - SPI1"]
    SPI1 = 26,
    #[doc = "27 - USART0"]
    USART0 = 27,
    #[doc = "28 - USART1"]
    USART1 = 28,
    #[doc = "32 - I2C0_ER"]
    I2C0_ER = 32,
    #[doc = "34 - I2C1_ER"]
    I2C1_ER = 34,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "Analog to digital converter"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4001_2400>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "Analog to digital converter"]
pub mod adc;
#[doc = "Comparator"]
pub type Cmp = crate::Periph<cmp::RegisterBlock, 0x4001_001c>;
impl core::fmt::Debug for Cmp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cmp").finish()
    }
}
#[doc = "Comparator"]
pub mod cmp;
#[doc = "cyclic redundancy check calculation unit"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "cyclic redundancy check calculation unit"]
pub mod crc;
#[doc = "Debug support"]
pub type Dbg = crate::Periph<dbg::RegisterBlock, 0x4001_5800>;
impl core::fmt::Debug for Dbg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dbg").finish()
    }
}
#[doc = "Debug support"]
pub mod dbg;
#[doc = "DMA controller"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "DMA controller"]
pub mod dma;
#[doc = "External interrupt/event controller"]
pub type Exti = crate::Periph<exti::RegisterBlock, 0x4001_0400>;
impl core::fmt::Debug for Exti {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Exti").finish()
    }
}
#[doc = "External interrupt/event controller"]
pub mod exti;
#[doc = "FMC"]
pub type Fmc = crate::Periph<fmc::RegisterBlock, 0x4002_2000>;
impl core::fmt::Debug for Fmc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fmc").finish()
    }
}
#[doc = "FMC"]
pub mod fmc;
#[doc = "free watchdog timer"]
pub type Fwdgt = crate::Periph<fwdgt::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Fwdgt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Fwdgt").finish()
    }
}
#[doc = "free watchdog timer"]
pub mod fwdgt;
#[doc = "General-purpose I/Os"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x4800_0000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "General-purpose I/Os"]
pub mod gpioa;
#[doc = "General-purpose I/Os"]
pub type Gpiob = crate::Periph<gpiob::RegisterBlock, 0x4800_0400>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "General-purpose I/Os"]
pub mod gpiob;
#[doc = "General-purpose I/Os"]
pub type Gpioc = crate::Periph<gpioc::RegisterBlock, 0x4800_0800>;
impl core::fmt::Debug for Gpioc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioc").finish()
    }
}
#[doc = "General-purpose I/Os"]
pub mod gpioc;
#[doc = "General-purpose I/Os"]
pub type Gpiof = crate::Periph<gpiof::RegisterBlock, 0x4800_1400>;
impl core::fmt::Debug for Gpiof {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiof").finish()
    }
}
#[doc = "General-purpose I/Os"]
pub mod gpiof;
#[doc = "Inter integrated circuit"]
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x4000_5400>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
#[doc = "Inter integrated circuit"]
pub mod i2c0;
#[doc = "Inter integrated circuit"]
pub type I2c1 = crate::Periph<i2c0::RegisterBlock, 0x4000_5800>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "Inter integrated circuit"]
pub use self::i2c0 as i2c1;
#[doc = "Power management unit"]
pub type Pmu = crate::Periph<pmu::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for Pmu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pmu").finish()
    }
}
#[doc = "Power management unit"]
pub mod pmu;
#[doc = "Reset and clock unit"]
pub type Rcu = crate::Periph<rcu::RegisterBlock, 0x4002_1000>;
impl core::fmt::Debug for Rcu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rcu").finish()
    }
}
#[doc = "Reset and clock unit"]
pub mod rcu;
#[doc = "Real-time clock"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4000_2800>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "Real-time clock"]
pub mod rtc;
#[doc = "Serial peripheral interface"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "Serial peripheral interface"]
pub mod spi0;
#[doc = "Serial Peripheral Interface 1"]
pub type Spi1 = crate::Periph<spi1::RegisterBlock, 0x4000_3800>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "Serial Peripheral Interface 1"]
pub mod spi1;
#[doc = "System configuration controller"]
pub type Syscfg = crate::Periph<syscfg::RegisterBlock, 0x4001_0000>;
impl core::fmt::Debug for Syscfg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Syscfg").finish()
    }
}
#[doc = "System configuration controller"]
pub mod syscfg;
#[doc = "Advanced-timers"]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0x4001_2c00>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "Advanced-timers"]
pub mod timer0;
#[doc = "General-purpose-timers"]
pub type Timer2 = crate::Periph<timer2::RegisterBlock, 0x4000_0400>;
impl core::fmt::Debug for Timer2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer2").finish()
    }
}
#[doc = "General-purpose-timers"]
pub mod timer2;
#[doc = "Basic-timers"]
pub type Timer5 = crate::Periph<timer5::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Timer5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer5").finish()
    }
}
#[doc = "Basic-timers"]
pub mod timer5;
#[doc = "General-purpose-timers"]
pub type Timer13 = crate::Periph<timer13::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Timer13 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer13").finish()
    }
}
#[doc = "General-purpose-timers"]
pub mod timer13;
#[doc = "General-purpose-timers"]
pub type Timer14 = crate::Periph<timer14::RegisterBlock, 0x4001_4000>;
impl core::fmt::Debug for Timer14 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer14").finish()
    }
}
#[doc = "General-purpose-timers"]
pub mod timer14;
#[doc = "General-purpose-timers"]
pub type Timer15 = crate::Periph<timer15::RegisterBlock, 0x4001_4400>;
impl core::fmt::Debug for Timer15 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer15").finish()
    }
}
#[doc = "General-purpose-timers"]
pub mod timer15;
#[doc = "General-purpose-timers"]
pub type Timer16 = crate::Periph<timer15::RegisterBlock, 0x4001_4800>;
impl core::fmt::Debug for Timer16 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer16").finish()
    }
}
#[doc = "General-purpose-timers"]
pub use self::timer15 as timer16;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type Usart0 = crate::Periph<usart0::RegisterBlock, 0x4001_3800>;
impl core::fmt::Debug for Usart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart0").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub mod usart0;
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub type Usart1 = crate::Periph<usart0::RegisterBlock, 0x4000_4400>;
impl core::fmt::Debug for Usart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart1").finish()
    }
}
#[doc = "Universal synchronous asynchronous receiver transmitter"]
pub use self::usart0 as usart1;
#[doc = "Window watchdog timer"]
pub type Wwdgt = crate::Periph<wwdgt::RegisterBlock, 0x4000_2c00>;
impl core::fmt::Debug for Wwdgt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wwdgt").finish()
    }
}
#[doc = "Window watchdog timer"]
pub mod wwdgt;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "CMP"]
    pub cmp: Cmp,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "DBG"]
    pub dbg: Dbg,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "EXTI"]
    pub exti: Exti,
    #[doc = "FMC"]
    pub fmc: Fmc,
    #[doc = "FWDGT"]
    pub fwdgt: Fwdgt,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "GPIOC"]
    pub gpioc: Gpioc,
    #[doc = "GPIOF"]
    pub gpiof: Gpiof,
    #[doc = "I2C0"]
    pub i2c0: I2c0,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "PMU"]
    pub pmu: Pmu,
    #[doc = "RCU"]
    pub rcu: Rcu,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "SYSCFG"]
    pub syscfg: Syscfg,
    #[doc = "TIMER0"]
    pub timer0: Timer0,
    #[doc = "TIMER2"]
    pub timer2: Timer2,
    #[doc = "TIMER5"]
    pub timer5: Timer5,
    #[doc = "TIMER13"]
    pub timer13: Timer13,
    #[doc = "TIMER14"]
    pub timer14: Timer14,
    #[doc = "TIMER15"]
    pub timer15: Timer15,
    #[doc = "TIMER16"]
    pub timer16: Timer16,
    #[doc = "USART0"]
    pub usart0: Usart0,
    #[doc = "USART1"]
    pub usart1: Usart1,
    #[doc = "WWDGT"]
    pub wwdgt: Wwdgt,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            adc: Adc::steal(),
            cmp: Cmp::steal(),
            crc: Crc::steal(),
            dbg: Dbg::steal(),
            dma: Dma::steal(),
            exti: Exti::steal(),
            fmc: Fmc::steal(),
            fwdgt: Fwdgt::steal(),
            gpioa: Gpioa::steal(),
            gpiob: Gpiob::steal(),
            gpioc: Gpioc::steal(),
            gpiof: Gpiof::steal(),
            i2c0: I2c0::steal(),
            i2c1: I2c1::steal(),
            pmu: Pmu::steal(),
            rcu: Rcu::steal(),
            rtc: Rtc::steal(),
            spi0: Spi0::steal(),
            spi1: Spi1::steal(),
            syscfg: Syscfg::steal(),
            timer0: Timer0::steal(),
            timer2: Timer2::steal(),
            timer5: Timer5::steal(),
            timer13: Timer13::steal(),
            timer14: Timer14::steal(),
            timer15: Timer15::steal(),
            timer16: Timer16::steal(),
            usart0: Usart0::steal(),
            usart1: Usart1::steal(),
            wwdgt: Wwdgt::steal(),
        }
    }
}
