#[doc = "Register `CTL1` reader"]
pub type R = crate::R<Ctl1Spec>;
#[doc = "Register `CTL1` writer"]
pub type W = crate::W<Ctl1Spec>;
#[doc = "DMA request source selection\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Dmas {
    #[doc = "0: DMA request is generated by capture/compare event"]
    CaptureOrCompare = 0,
    #[doc = "1: DMA request is generated by update event"]
    Update = 1,
}
impl From<Dmas> for bool {
    #[inline(always)]
    fn from(variant: Dmas) -> Self {
        variant as u8 != 0
    }
}
#[doc = "Field `DMAS` reader - DMA request source selection"]
pub type DmasR = crate::BitReader<Dmas>;
impl DmasR {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub const fn variant(&self) -> Dmas {
        match self.bits {
            false => Dmas::CaptureOrCompare,
            true => Dmas::Update,
        }
    }
    #[doc = "DMA request is generated by capture/compare event"]
    #[inline(always)]
    pub fn is_capture_or_compare(&self) -> bool {
        *self == Dmas::CaptureOrCompare
    }
    #[doc = "DMA request is generated by update event"]
    #[inline(always)]
    pub fn is_update(&self) -> bool {
        *self == Dmas::Update
    }
}
#[doc = "Field `DMAS` writer - DMA request source selection"]
pub type DmasW<'a, REG> = crate::BitWriter<'a, REG, Dmas>;
impl<'a, REG> DmasW<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    #[doc = "DMA request is generated by capture/compare event"]
    #[inline(always)]
    pub fn capture_or_compare(self) -> &'a mut crate::W<REG> {
        self.variant(Dmas::CaptureOrCompare)
    }
    #[doc = "DMA request is generated by update event"]
    #[inline(always)]
    pub fn update(self) -> &'a mut crate::W<REG> {
        self.variant(Dmas::Update)
    }
}
#[doc = "Master mode control\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Mmc {
    #[doc = "0: When a counter reset event occurs, a TRGO trigger signal is output. The counter resert source: Master timer generate a reset the UPG bit in the TIMERx_SWEVG register is set"]
    Mode0 = 0,
    #[doc = "1: Enable. When a conter start event occurs, a TRGO trigger signal is output. The counter start source : CEN control bit is set The trigger input in pause mode is high"]
    Mode1 = 1,
    #[doc = "2: When an update event occurs, a TRGO trigger signal is output. The update source depends on UPDIS bit and UPS bit."]
    Mode2 = 2,
    #[doc = "3: When a capture or compare pulse event occurs in channel0, a TRGO trigger signal is output."]
    Mode3 = 3,
    #[doc = "4: When a compare event occurs, a TRGO trigger signal is output. The compare source is from O0CPRE."]
    Mode4 = 4,
    #[doc = "5: When a compare event occurs, a TRGO trigger signal is output. The compare source is from O1CPRE."]
    Mode5 = 5,
    #[doc = "6: When a compare event occurs, a TRGO trigger signal is output. The compare source is from O2CPRE."]
    Mode6 = 6,
    #[doc = "7: When a compare event occurs, a TRGO trigger signal is output. The compare source is from O3CPRE."]
    Mode7 = 7,
}
impl From<Mmc> for u8 {
    #[inline(always)]
    fn from(variant: Mmc) -> Self {
        variant as _
    }
}
impl crate::FieldSpec for Mmc {
    type Ux = u8;
}
impl crate::IsEnum for Mmc {}
#[doc = "Field `MMC` reader - Master mode control"]
pub type MmcR = crate::FieldReader<Mmc>;
impl MmcR {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub const fn variant(&self) -> Mmc {
        match self.bits {
            0 => Mmc::Mode0,
            1 => Mmc::Mode1,
            2 => Mmc::Mode2,
            3 => Mmc::Mode3,
            4 => Mmc::Mode4,
            5 => Mmc::Mode5,
            6 => Mmc::Mode6,
            7 => Mmc::Mode7,
            _ => unreachable!(),
        }
    }
    #[doc = "When a counter reset event occurs, a TRGO trigger signal is output. The counter resert source: Master timer generate a reset the UPG bit in the TIMERx_SWEVG register is set"]
    #[inline(always)]
    pub fn is_mode0(&self) -> bool {
        *self == Mmc::Mode0
    }
    #[doc = "Enable. When a conter start event occurs, a TRGO trigger signal is output. The counter start source : CEN control bit is set The trigger input in pause mode is high"]
    #[inline(always)]
    pub fn is_mode1(&self) -> bool {
        *self == Mmc::Mode1
    }
    #[doc = "When an update event occurs, a TRGO trigger signal is output. The update source depends on UPDIS bit and UPS bit."]
    #[inline(always)]
    pub fn is_mode2(&self) -> bool {
        *self == Mmc::Mode2
    }
    #[doc = "When a capture or compare pulse event occurs in channel0, a TRGO trigger signal is output."]
    #[inline(always)]
    pub fn is_mode3(&self) -> bool {
        *self == Mmc::Mode3
    }
    #[doc = "When a compare event occurs, a TRGO trigger signal is output. The compare source is from O0CPRE."]
    #[inline(always)]
    pub fn is_mode4(&self) -> bool {
        *self == Mmc::Mode4
    }
    #[doc = "When a compare event occurs, a TRGO trigger signal is output. The compare source is from O1CPRE."]
    #[inline(always)]
    pub fn is_mode5(&self) -> bool {
        *self == Mmc::Mode5
    }
    #[doc = "When a compare event occurs, a TRGO trigger signal is output. The compare source is from O2CPRE."]
    #[inline(always)]
    pub fn is_mode6(&self) -> bool {
        *self == Mmc::Mode6
    }
    #[doc = "When a compare event occurs, a TRGO trigger signal is output. The compare source is from O3CPRE."]
    #[inline(always)]
    pub fn is_mode7(&self) -> bool {
        *self == Mmc::Mode7
    }
}
#[doc = "Field `MMC` writer - Master mode control"]
pub type MmcW<'a, REG> = crate::FieldWriter<'a, REG, 3, Mmc, crate::Safe>;
impl<'a, REG> MmcW<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
    REG::Ux: From<u8>,
{
    #[doc = "When a counter reset event occurs, a TRGO trigger signal is output. The counter resert source: Master timer generate a reset the UPG bit in the TIMERx_SWEVG register is set"]
    #[inline(always)]
    pub fn mode0(self) -> &'a mut crate::W<REG> {
        self.variant(Mmc::Mode0)
    }
    #[doc = "Enable. When a conter start event occurs, a TRGO trigger signal is output. The counter start source : CEN control bit is set The trigger input in pause mode is high"]
    #[inline(always)]
    pub fn mode1(self) -> &'a mut crate::W<REG> {
        self.variant(Mmc::Mode1)
    }
    #[doc = "When an update event occurs, a TRGO trigger signal is output. The update source depends on UPDIS bit and UPS bit."]
    #[inline(always)]
    pub fn mode2(self) -> &'a mut crate::W<REG> {
        self.variant(Mmc::Mode2)
    }
    #[doc = "When a capture or compare pulse event occurs in channel0, a TRGO trigger signal is output."]
    #[inline(always)]
    pub fn mode3(self) -> &'a mut crate::W<REG> {
        self.variant(Mmc::Mode3)
    }
    #[doc = "When a compare event occurs, a TRGO trigger signal is output. The compare source is from O0CPRE."]
    #[inline(always)]
    pub fn mode4(self) -> &'a mut crate::W<REG> {
        self.variant(Mmc::Mode4)
    }
    #[doc = "When a compare event occurs, a TRGO trigger signal is output. The compare source is from O1CPRE."]
    #[inline(always)]
    pub fn mode5(self) -> &'a mut crate::W<REG> {
        self.variant(Mmc::Mode5)
    }
    #[doc = "When a compare event occurs, a TRGO trigger signal is output. The compare source is from O2CPRE."]
    #[inline(always)]
    pub fn mode6(self) -> &'a mut crate::W<REG> {
        self.variant(Mmc::Mode6)
    }
    #[doc = "When a compare event occurs, a TRGO trigger signal is output. The compare source is from O3CPRE."]
    #[inline(always)]
    pub fn mode7(self) -> &'a mut crate::W<REG> {
        self.variant(Mmc::Mode7)
    }
}
#[doc = "Channel 0 trigger input selection\n\nValue on reset: 0"]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Ti0s {
    #[doc = "0: TIMERx_CH0 is selected as channel 0 trigger input"]
    Ch0 = 0,
    #[doc = "1: The result of combinational XOR of TIMERx_CH0, TIMERx_CH1, TIMERx_CH2 is selected as channel 0 trigger input"]
    Multi = 1,
}
impl From<Ti0s> for bool {
    #[inline(always)]
    fn from(variant: Ti0s) -> Self {
        variant as u8 != 0
    }
}
#[doc = "Field `TI0S` reader - Channel 0 trigger input selection"]
pub type Ti0sR = crate::BitReader<Ti0s>;
impl Ti0sR {
    #[doc = "Get enumerated values variant"]
    #[inline(always)]
    pub const fn variant(&self) -> Ti0s {
        match self.bits {
            false => Ti0s::Ch0,
            true => Ti0s::Multi,
        }
    }
    #[doc = "TIMERx_CH0 is selected as channel 0 trigger input"]
    #[inline(always)]
    pub fn is_ch0(&self) -> bool {
        *self == Ti0s::Ch0
    }
    #[doc = "The result of combinational XOR of TIMERx_CH0, TIMERx_CH1, TIMERx_CH2 is selected as channel 0 trigger input"]
    #[inline(always)]
    pub fn is_multi(&self) -> bool {
        *self == Ti0s::Multi
    }
}
#[doc = "Field `TI0S` writer - Channel 0 trigger input selection"]
pub type Ti0sW<'a, REG> = crate::BitWriter<'a, REG, Ti0s>;
impl<'a, REG> Ti0sW<'a, REG>
where
    REG: crate::Writable + crate::RegisterSpec,
{
    #[doc = "TIMERx_CH0 is selected as channel 0 trigger input"]
    #[inline(always)]
    pub fn ch0(self) -> &'a mut crate::W<REG> {
        self.variant(Ti0s::Ch0)
    }
    #[doc = "The result of combinational XOR of TIMERx_CH0, TIMERx_CH1, TIMERx_CH2 is selected as channel 0 trigger input"]
    #[inline(always)]
    pub fn multi(self) -> &'a mut crate::W<REG> {
        self.variant(Ti0s::Multi)
    }
}
impl R {
    #[doc = "Bit 3 - DMA request source selection"]
    #[inline(always)]
    pub fn dmas(&self) -> DmasR {
        DmasR::new(((self.bits >> 3) & 1) != 0)
    }
    #[doc = "Bits 4:6 - Master mode control"]
    #[inline(always)]
    pub fn mmc(&self) -> MmcR {
        MmcR::new(((self.bits >> 4) & 7) as u8)
    }
    #[doc = "Bit 7 - Channel 0 trigger input selection"]
    #[inline(always)]
    pub fn ti0s(&self) -> Ti0sR {
        Ti0sR::new(((self.bits >> 7) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 3 - DMA request source selection"]
    #[inline(always)]
    pub fn dmas(&mut self) -> DmasW<'_, Ctl1Spec> {
        DmasW::new(self, 3)
    }
    #[doc = "Bits 4:6 - Master mode control"]
    #[inline(always)]
    pub fn mmc(&mut self) -> MmcW<'_, Ctl1Spec> {
        MmcW::new(self, 4)
    }
    #[doc = "Bit 7 - Channel 0 trigger input selection"]
    #[inline(always)]
    pub fn ti0s(&mut self) -> Ti0sW<'_, Ctl1Spec> {
        Ti0sW::new(self, 7)
    }
}
#[doc = "control register 1\n\nYou can [`read`](crate::Reg::read) this register and get [`ctl1::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`ctl1::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct Ctl1Spec;
impl crate::RegisterSpec for Ctl1Spec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`ctl1::R`](R) reader structure"]
impl crate::Readable for Ctl1Spec {}
#[doc = "`write(|w| ..)` method takes [`ctl1::W`](W) writer structure"]
impl crate::Writable for Ctl1Spec {
    type Safety = crate::Unsafe;
}
#[doc = "`reset()` method sets CTL1 to value 0"]
impl crate::Resettable for Ctl1Spec {}
